project_name: ops-mcp-server
before:
  hooks:
    - go mod download
    - go mod tidy
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/server/main.go
    binary: ops-mcp-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    tags: containers_image_openpgp
    ldflags:
      - -X "github.com/shaowenchen/ops-mcp-server/cmd/version.BuildVersion={{ .Version }}"
      - -X "github.com/shaowenchen/ops-mcp-server/cmd/version.BuildDate={{ .Date }}"
      - -X "github.com/shaowenchen/ops-mcp-server/cmd/version.GitCommitID={{ .ShortCommit }}"
      - -w
      - -s
dist: bin
archives:
  - name_template: "ops-mcp-server-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
changelog:
  skip: true
