apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-mcp-server-config
  labels:
    app: ops-mcp-server
    component: config
data:
  config.yaml: |
    # Ops MCP Server Configuration
    # This configuration file provides settings for the modular MCP server

    # Logging configuration
    log_level: info

    # Server configuration
    server:
      host: 0.0.0.0
      port: 3000
      mode: sse  # Server mode: "stdio" or "sse" (use sse for k8s deployment)

    # Module configurations
    # Each module can be enabled/disabled and configured independently

    # Events module - provides event querying capabilities
    events:
      enabled: true
      endpoint: "http://localhost:3000/api/v1/events"
      token: ""

    # Metrics module - provides metrics monitoring capabilities  
    metrics:
      enabled: true

    # Logs module - provides log analysis capabilities
    logs:
      enabled: true

    # SSE configuration
    sse:
      keepAlive: 30s
      maxConnections: 1000

    # Authentication configuration (placeholder)
    auth:
      enabled: false 