apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-mcp-server
  namespace: ops-system
  labels:
    app: ops-mcp-server
    version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ops-mcp-server
  template:
    metadata:
      labels:
        app: ops-mcp-server
        version: v1.0.0
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ops-mcp-server
          image: registry.cn-beijing.aliyuncs.com/opshub/shaowenchen-ops-mcp-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SERVER_MODE
              value: "sse"
            - name: EVENTS_ENABLED
              value: "true"
            - name: EVENTS_ENDPOINT
              value: "https://ops-server.your-company.com"
            - name: EVENTS_API_TOKEN
              value: ""
            - name: METRICS_ENABLED
              value: "true"
            - name: METRICS_PROMETHEUS_ENDPOINT
              value: "https://prometheus.your-company.com"
            - name: LOGS_ENABLED
              value: "true"
            - name: LOGS_ELASTICSEARCH_ENDPOINT
              value: "https://elasticsearch.your-company.com"
            - name: ELASTICSEARCH_USER
              value: ""
            - name: ELASTICSEARCH_PASSWORD
              value: ""
            - name: AUTH_ENABLED
              value: "false"
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      terminationGracePeriodSeconds: 30
